name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: |
          npm ci
          cd frontend
          npm ci
          npm run build
          cd ..
          pm2 stop 0
          pm2 start 0 
          pm2 save
          sudo service nginx restart
